apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: praveenkumar-reddy
spec:
  finally:
    - name: sendmail-notification-succeeded
      taskRef:
        kind: Task
        name: send-pipeline-logs-2
      when:
        - input: Failed
          operator: notin
          values:
            - $(tasks.source-clone.status)
            - $(tasks.junit-tests.status)
            - $(tasks.get-version.status)
            - $(tasks.release-app.status)
            - $(tasks.build.status)
            - $(tasks.git-update-deployment.status)
            - $(tasks.git-update-deployment-2.status)
      workspaces:
        - name: mail
          workspace: workspace
    - name: sendmail-notification-failed
      taskRef:
        kind: Task
        name: send-pipeline-logs-2
      when:
        - input: Failed
          operator: in
          values:
            - $(tasks.source-clone.status)
            - $(tasks.junit-tests.status)
            - $(tasks.get-version.status)
            - $(tasks.release-app.status)
            - $(tasks.build.status)
            - $(tasks.git-update-deployment.status)
            - $(tasks.git-update-deployment-2.status)
      workspaces:
        - name: mail
          workspace: workspace
  params:
    - default: 'https://github.com/praveenrachamreddy/sample-web-application.git'
      description: The application git repository
      name: APP_SOURCE_GIT
      type: string
    - default: ansible-sonar
      description: The application git revision
      name: APP_SOURCE_REVISION
      type: string
    - default: quay.io/praveenrachamreddy/ci-pipeline
      name: IMAGE
      type: string
    - default: DEV
      name: TAG
      type: string
    - default: TEST
      name: NEW_TAG
      type: string
    - default: 'https://github.com/praveenrachamreddy/WebApp-config.git'
      description: The application configuration git repository
      name: APP_CONFIG_GIT
      type: string
  tasks:
    - name: source-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: junit-tests
      params:
        - name: GOALS
          value:
            - test
      runAfter:
        - source-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: code-analysis
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - source-clone
      workspaces:
      - name: source
        workspace: workspace
      - name: maven-settings
        workspace: maven-settings
      params:
      - name: GOALS
        value:
        - sonar:sonar
    - name: get-version
      runAfter:
        - junit-tests
        - code-analysis
      taskRef:
        kind: Task
        name: maven-get-project-version
      workspaces:
        - name: source
          workspace: workspace
    - name: release-app
      params:
        - name: GOALS
          value:
            - package
            - deploy
      runAfter:
        - get-version
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build
      params:
        - name: IMAGE
          value: '$(params.IMAGE):$(tasks.get-version.results.version)-$(params.TAG)'
      runAfter:
        - release-app
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: $(params.APP_CONFIG_GIT)
        - name: CURRENT_IMAGE
          value: quay.io/praveenrachamreddy/ci-pipeline
        - name: NEW_IMAGE
          value: '$(params.IMAGE):$(tasks.get-version.results.version)-$(params.TAG)'
        - name: NEW_DIGEST
          value: $(tasks.build.results.IMAGE_DIGEST)
        - name: KUSTOMIZATION_PATH
          value: app
      runAfter:
        - build
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: workspace
    - name: git-update-deployment-2
      params:
        - name: GIT_REPOSITORY
          value: $(params.APP_CONFIG_GIT)
        - name: CURRENT_IMAGE
          value: quay.io/praveenrachamreddy/ci-pipeline
        - name: NEW_IMAGE
          value: '$(params.IMAGE):$(tasks.get-version.results.version)-$(params.NEW_TAG)'
        - name: NEW_TAG
          value: $(params.NEW_TAG)
        - name: KUSTOMIZATION_PATH
          value: app
      runAfter:
        - git-update-deployment
      taskRef:
        kind: Task
        name: git-update-deployment-2
      workspaces:
        - name: workspace
          workspace: workspace
      
  workspaces:
    - name: workspace
    - name: maven-settings
