apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: pkr-demo
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDZERWRU9hWjBsYThEWUdzMXg4QnQ3TlFOZkoxNXVxbThLR2kxd1hoMURQd0FBQUppQTVtMDdnT1p0Ck93QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ2REVkVPYVowbGE4RFlHczF4OEJ0N05RTmZKMTV1cW04S0dpMXdYaDFEUHcKQUFBRUJWYjRtVGl5SnBFTThXVkJ2Q1E1OFMyTkZQbmlFVVpPT00vV1k1R0ZJUjA1ME5VUTVwblNWcndOZ2F6WEh3RzNzMQpBMThuWG02cWJ3b2FMWEJlSFVNL0FBQUFFbkp2YjNSQWIyTndOQzVwYlhOekxtTnZiUUVDQXc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K