apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail
spec:
  description: This task sends a simple email to receivers via SMTP server
  params:
    - default: server-secret
      description: 'secret name for SMTP server information (url, port, password)'
      name: server
      type: string
    - default: ci-pipeline
      description: plain text email subject
      name: subject
      type: string
    - default: hi Build sucess
      description: plain text email body
      name: body
      type: string
    - default: rachamreddypraveen@gmail.com
      description: sender email address
      name: sender
      type: string
    - default: rachamreddypraveen2@gmail.com
      description: recipient email addresses (space delimited list)
      name: recipients
      type: string
  steps:
    - env:
        - name: USER
          valueFrom:
            secretKeyRef:
              key: user
              name: server-secret
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: server-secret
        - name: TLS
          valueFrom:
            secretKeyRef:
              key: tls
              name: server-secret
        - name: SERVER
          valueFrom:
            secretKeyRef:
              key: url
              name: server-secret
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: server-secret
      image: >-
        docker.io/library/python:3.8-alpine@sha256:e11bbd37d4371894e954421b85dbe8dd4eb7198d7cb4ed144ab529f19f57c3f1
      name: send
      resources: {}
      script: |
        #!/usr/bin/env python3
        import smtplib, ssl, os
        port = os.getenv('PORT')
        smtp_server = os.getenv('SERVER')
        sender_email = "$(params.sender)"
        receiver_emails = "$(params.recipients)"
        user = os.getenv('USER')
        password = os.getenv('PASSWORD')
        tls = os.getenv('TLS')
        message = f"""\
        Subject: $(params.subject)
        To: {receiver_emails}
        From: {sender_email}

        $(params.body)"""
        print(message)
        if tls == 'True':
            context = ssl.create_default_context()
            server = smtplib.SMTP_SSL(smtp_server, port, context=context)
        else:
            server = smtplib.SMTP(smtp_server, port)
        if password != '':
            server.login(user, password)
        for receiver in [item for item in receiver_emails.split(' ') if item]:
            server.sendmail(sender_email, receiver, message.encode('utf-8'))
        server.quit()
