apiVersion: maistra.io/v2 
kind: ServiceMeshControlPlane 
metadata:
  name: basic
spec: 
  version: v2.3
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits: 
        cpu: 500m 
        memory: 128Mi 
  tracing:
    type: Jaeger
  gateways: 
    ingress: 
      service: 
        type: ClusterIP
        ports:
        - name: status-port
          port: 15020 
        - name: http2
          port: 80 
          targetPort: 8080
        - name: https
          port: 443 
          targetPort: 8443
      meshExpansionPorts: []
    egress: 
      service:
        type: ClusterIP 
        ports:
        - name: status-port
          port: 15020 
        - name: http2
          port: 80
          targetPort: 8080 
        - name: https 
          port: 443 
          targetPort: 8443 
  policy: 
    type: Istiod 
  telemetry: 
    type: Istiod 
  addons: 
    prometheus: 
      enabled: true 
    grafana:
      enabled: true 
      install: 
        config: 
          env: {} 
          envSecrets: {} 
        service: 
          ingress: 
            contextPath: /grafana 
            tls: 
              termination: reencrypt 
    kiali: 
      name: kiali 
      enabled: true 
      install: 
        dashboard: 
          viewOnly: false 
          enableGrafana: true 
          enableTracing: true 
          enablePrometheus: true 
      service: 
        ingress: 
          contextPath: /kiali 
    jaeger: 
      name: jaeger 
      install: 
        storage: 
          type: Elasticsearch 
          elasticsearch: 
            nodeCount: 3 
            storage:
              storageClassName: app-thin-csi 
              size: 200Gi 
            redundancyPolicy: ZeroRedundancy 
            indexCleaner: 
              enabled: true
              numberOfDays: 15
              schedule: "55 23 * * *" 
        ingress: {} 
  runtime: 
    components: 
      tracing.jaeger.elasticsearch: 
        container: 
          resources: 
            requests:
              cpu: "1" 
              memory: "8Gi"
            limits: 
              cpu: "2" 
              memory: "10Gi"


