apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mail-taskrun
spec:
  params:
  - name: server
    value: server-secret
  - name: subject
    value: Hi, again!
  - name: body
    value: "Tekton email"
  - name: sender
    value: "rachamreddypraveen@gmail.com"
  - name: recipients
    value: "rachamreddypraveen2@gmail.com"
  taskRef:
    name: sendmail